// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.subsystems;


import frc.robot.Limelight;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
import com.ctre.phoenix.sensors.PigeonIMU;
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.PowerDistributionPanel;

public class Chassis extends Subsystem {

    public PigeonIMU pigeon;
    public PowerDistributionPanel pDP;
    public Compressor compressor;

    public String frontLimeKey = "limelight";
    public String backLimeKey = "limelight-one";
    public Limelight frontLime;
    public Limelight backLime;

    public Chassis() {
        pigeon = new PigeonIMU(2);

        frontLime = new Limelight(frontLimeKey);
        backLime = new Limelight(backLimeKey);
    }

    @Override
    public void initDefaultCommand() {
        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop
        frontLime.update(frontLimeKey);
        backLime.update(backLimeKey);
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

