// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.subsystems;


import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.DoubleSolenoid.Value;
import edu.wpi.first.wpilibj.command.Subsystem;

public class Manipulator extends Subsystem {

    public DoubleSolenoid claw;
    public DoubleSolenoid pusher;

    public Manipulator() {
        claw = new DoubleSolenoid(0, 4, 5);
        addChild("Claw",claw);
        
        pusher = new DoubleSolenoid(0, 6, 7);
        addChild("Pusher",pusher);
        
        setPusher(false);
    }

    @Override
    public void initDefaultCommand() {
        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop
    }


    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public boolean getIsOpen(){
        return claw.get()==Value.kReverse;
    }
    public boolean getIsPushing(){
        return pusher.get()==Value.kReverse;
    }

    public void setClaw(boolean extend){
        Value state = (extend)? Value.kReverse:Value.kForward;
        claw.set(state);
    }

    public void setPusher(boolean extend){
        Value state = (extend)? Value.kReverse:Value.kForward;
        pusher.set(state);
    }

}

