// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.subsystems.driveCommands;

import edu.wpi.first.wpilibj.command.Command;
import frc.robot.Robot;
import frc.robot.common.Limelight;
import frc.robot.common.Network;
public class VisionForwardTarget extends Command {

    private Limelight lime;
    private final double safeArea = 6.2;//percent area when close

    public VisionForwardTarget() {
        requires(Robot.drive);
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
        lime = Robot.chassis.frontLime;
        Robot.drive.shiftSet(1);
        lime.lightOn();
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
        double area = (lime.getTa());
        double limeForward = 0.4*((safeArea-area)/safeArea);
        Network.put("Target Distance", area);
        if(lime.getTv()==1) Robot.drive.setForward(limeForward);
        else Robot.drive.setForward(0);
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return (lime.getTv()==1 && lime.getTa()>=safeArea) || Robot.arm.getButton();
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
        Robot.drive.setDrive(0,0);
        Robot.drive.shiftDefault();
        lime.lightOff();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
        end();
    }
}
